name: Label Event
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'bug'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hola ${{ github.event.issue.user.login }} 👋
            ¿Encontraste un bug? Llamando a @BGMP para poder arreglar esto!!!
        
            ![Bug](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExMzFyb203amx2b2k2eXozMzRhZTEzbHhuaGlvcnRuNzVqY3U0YjU3biZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/26DOMIeH5yZgc4GD6/giphy.gif)
          
